__include__: ['base_config.yaml']

# Reproduces Karthay's original nanogpt run but for 10.7B tokens
# eval settings same as Karpathy's llm.c with no checkpointing

general:
  project_name: 'gpt2_owt'

data:
  module_kwargs:
    tokenized_train_path: '$DATA_ROOT/tokenized/openwebtext/tiktoken/train.bin'
    tokenized_val_path: '$DATA_ROOT/tokenized/openwebtext/tiktoken/val.bin'
    eval_batch_size: 32 # same as llm.c

training:
  device_batch_size: 60 # default is 12 to match original nanogpt, should be 32 to match llm.c, can fit 60 on 192GB
  # some runs uses 23148 with 480 global batch size yielding 11.3777
  # for 480 global batch size, use 21701 to match 10.6665B tokens
  # for 512 global batch size, use 20345 to match 10.6666B tokens
  max_steps: 21701
  global_batch_size: 480 # original nanogpt 480, llm.c 512

eval:
  eval_every: 250
  eval_iters: 1600 # 200*8 workers
  save_checkpoint: false
  checkoint_after: 0 # starts saving checkpoint after these steps
  checkpoint_every_hr: 200 # take checkpoint every this hours
  checkpoint_keep_best: false # keep only the best checkpoint, otherwise keep all with  _{step}.pt
