__include__: ['base_config.yaml']

# Use prime 223 but with nanoGPT style model instead of author's original model

model:
  module: 'nanugpt.models.tiny_transformer.get_model'

tokenizer:
  module: 'nanugpt.tokenizers.grokking_tokenizer.get_tokenizer'

optimizer:
  module: 'nanugpt.optimizers.adam_w.get_optim'

scheduler:
  module: 'nanugpt.schedulers.constant.get_scheduler'

